version: "3"
services:
  php:
    image: php:v1
    ports:
      - 81:80
    depends_on:
      - mysql
  mysql:
    image: mysql:v1
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: password
volumes:
  db_data: {}
